global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using Coffee.Domain.Commands;
global using Coffee.Domain.Commands.UserCommands;
global using Coffee.Domain.Enums;
global using Coffee.Domain.Models.User;
global using Coffee.Domain.ValueObjects;
global using Coffee.Domain.Handlers.UserHandlers;
global using Coffee.Tests.Repositories;
global using Coffee.Tests.Services;
